### ISSUE TITLE
cannot import name OUTPUT_STYLES

### ISSUE THREAD

**Issue by adamlwgriffiths** [dahlia/libsass-python#136]
Running sass or sassc results in the following errors:

```
$ sassc
Traceback (most recent call last):
  File "/home/<snip>/.anaconda/envs/systema/bin/sassc", line 9, in <module>
    load_entry_point('libsass==0.10.1', 'console_scripts', 'sassc')()
  File "/home/<snip>/.anaconda/envs/systema/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/<snip>/.anaconda/envs/systema/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/home/<snip>/.anaconda/envs/systema/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/home/<snip>/.anaconda/envs/systema/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/<snip>/.anaconda/envs/systema/bin/sassc.py", line 71, in <module>
    from sass import __version__ as VERSION, OUTPUT_STYLES, CompileError, compile
ImportError: cannot import name OUTPUT_STYLES
```

```
$ pip freeze | grep libsass
libsass==0.10.1
$ python --version
Python 2.7.10 :: Continuum Analytics, Inc.
```

**Comment by asottile** [comment]
Let's continue this in #137 . I imagine they are the same root cause
