### ISSUE TITLE
can't compile input[type=url]

### ISSUE THREAD

**Issue by fcpauldiaz** [dahlia/libsass-python#210]
I'm trying to compile the [materialize](http://materializecss.com/) project but it only compiles when I remove the `input[type=url] ` line

```sass
input[type=text]:not(.browser-default),
input[type=password]:not(.browser-default),
input[type=email]:not(.browser-default),
input[type=url]:not(.browser-default),  // I have to remove this line to compile it
input[type=time]:not(.browser-default),
input[type=date]:not(.browser-default),
input[type=datetime]:not(.browser-default),
input[type=datetime-local]:not(.browser-default),
input[type=tel]:not(.browser-default),
input[type=number]:not(.browser-default),
input[type=search]:not(.browser-default),
textarea.materialize-textarea { // rules go here }
```

This is the trace
```bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 103, in handle
    self.parse_template(template_name)
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 269, in parse_template
    self.compile_sass(sass_filename)
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 287, in compile_sass
    content = sass.compile(**compile_kwargs)
  File "/Users/SDX/Documents/Django/env_keydex/lib/python2.7/site-packages/sass.py", line 640, in compile
    raise CompileError(v)
sass.CompileError: Error: Invalid CSS after "}": expected 1 selector or at-rule, was "input[type=text]:no"
        on line 20 of keydex/static/sass/components/forms/_input-fields.scss
>> }
```

**Comment by asottile** [comment]
This is probably due to `libsass` itself (as we're a simple wrapper)

This issue looks related: https://github.com/sass/libsass/issues/2427

I'll open another on upstream as well

**Comment by asottile** [comment]
I've opened https://github.com/sass/libsass/issues/2429

For now, you can probably use `libsass==0.12.3` as a workaround

**Comment by asottile** [comment]
I'm going to close this since it's not our bug but upstream's -- please track the two linked issues and when an upstream release is made we'll incorporate those changes :)

**Comment by asottile** [comment]
I believe 0.13.3 has a fix for this!
