### ISSUE TITLE
Installed but DLL load failed

### ISSUE THREAD

**Issue by sherwyngoh** [dahlia/libsass-python#85]
On Windows, Python 3.4 64bit.

pip install libsass
Requirement already satisfied (use --upgrade to upgrade): libsass in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): six in c:\python34\lib\site-packages (from libsass)

> python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\sass.py", line 24, in <module>
    from _sass import OUTPUT_STYLES, compile_filename, compile_string
ImportError: DLL load failed: %1 is not a valid Win32 application.
>>>

Help!

**Comment by sherwyngoh** [comment]
I'm not sure if there is a way to inform the user that the installation is not appropriate for the version.
I found the right file to custom install it

https://pypi.python.org/pypi/libsass

I'll be adding to the readme
